import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

const querClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={querClient}>
        <body className={poppins.className}>
          <Header />
          {children}
        </body>
      </QueryClientProvider>
    </html>
  );
}
